name: Nightly Memory Miner

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  memory-mine:
    if: ${{ secrets.DATABASE_URL != '' }}
    runs-on: ubuntu-latest
    env:
      MEMORY_ENABLED: '1'
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run memory miner
        run: pnpm mem:mine
